---

- hosts: all
  become: true
  tasks:

  # "package" below will automatically use the default package manager for the system (Ubuntu -> apt, CentOS -> dnf)
  - name: install apache and php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    
 #here is the added below playbook for CentOS servers
 #CentOS does not use apt -> dnf instead
 #It also does not use apache2 -> httpd instead

