---

- hosts: all
  become: true #use this piece here for sudo permissions
  pre_tasks:

  - name: install updates(CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
        upgrade: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
    
    - name: install unzip
      package: 
        name: unzip
    
    - name: install terraform
      unarchive: 
        src: https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes #this piece is required to let it know that src is not local (it doesn't know even thought it says https above)
        mode: 0755
        owner: root
        group: root



- hosts: web_servers
  become: true
  tasks:  

    - name: install apache and php for Ubuntu servers
      tags: apache, apache2, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for CentOS servers
      tags: apache, centos, httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: start httpd (CentOS)
      tags: apache, centos, httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS" 
    
    #this can change the line in config file within the server-file
    - name: change e-mail address for admin
      tags: apache, centos, httpd
      lineinfile:  
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin' #says we want to edit line with 'ServerAdmin' starting off
        line: ServerAdmin somebody@somewhere.net #what to replace line with
      when: ansible_distribution == "CentOS"
      register: httpd #saves state in variable httpd here
  
    #this play will restart httpd service
    - name: restart httpd (CentOS)
      tags: apache, centos, httpd
      service: 
        name: httpd 
        state: restarted
      when: httpd.changed #only restart service when httpd register (as seen above) is changed

    - name: copy default html file for site
      tags: apache, apache2, httpd
      copy:
        src: default_site.html #directory of file is assumed, you don't need to include it
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644 #set permissions of that file

- hosts: db_servers
  become: true
  tasks:
    
    - name: install mariadb package (CentOS)
      tags: centos, db, mariadb
      dnf: 
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: mariadb, db, ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu" 

- hosts: file_servers
  become: true
  tasks:
  
    - name: install samba packagea
      tags: samba
      package:
        name: samba
        state: latest
